### ISSUE TITLE
(물리모드) 낮은 확률로 윷끼리 겹칠시 끝나지 않음

### ISSUE THREAD

**Issue by Kill00** [LowQuality/YutNori#16]

**Comment by Kill00** [comment]
![Bug](https://user-images.githubusercontent.com/70481054/194738121-1f1100f9-798d-4269-8c32-320afa44de10.PNG)

**Comment by HelloWorld-0code0** [comment]
![Screenshot_20221009-133517_Chrome](https://user-images.githubusercontent.com/97296959/194738283-e9ab760e-e5f2-4d17-a2d2-0d456ea40640.jpg)
